### ISSUE TITLE
Prob_Obs_Test doesn't work for Identifiability and Observability Analysis

### ISSUE THREAD

**Issue by simon-hellmann** [afvillaverde/strike-goldd#11]
Hi everyone! 

I'm new to StrikeGoldd, and perhaps I'm making a stupid mistake, so please bear with me.

I used the FISPO-algorithm to analyze some standard models already given in the "models" folder that comes with the toolbox (C2M, HIV, 2DOF). They all worked out fine. 

However, if I set the switch `opts.algorithm = 2` (Prob_Obs_Test) in options.m and leave everything else unchanged, Matlab always gives me the following error (regardless which of the rational models I use): 

```
Brace indexing is not supported for variables of this type.

Error in sym/subsref (line 898)
            R_tilde = builtin('subsref',L_tilde,Idx);

Error in rational2polinomial (line 52)
        c=[c{:}];

Error in calcLVS (line 20)
    P(i)=rational2polinomial(P(i));

Error in build_OI_sed (line 54)
LVS=calcLVS(x,xd,p,f,VSM,VSMd,n,q);

Error in prob_obs_test (line 163)
[onx]=build_OI_sed(Myprime,x,p,u,h,f,n,q,nu,m,opts);

Error in STRIKE_GOLDD (line 60)
        prob_obs_test(modelname,opts,prev_ident_pars,nmf);
```

I use Matlab R2020a and have the System Identification Toolbox Version 9.12. 
I'd appreciate any support. Thank you!

**Comment by afvillaverde** [comment]
Hi Simon,
Thanks for reporting this issue, and apologies for our late reply, which was due to the vacation period.
We have modified the code and we believe that this issue is fixed now. Could you please download the latest version of the toolbox, and check if you still get an error?

**Comment by simon-hellmann** [comment]
Hi Alejandro, 
thank you for your prompt response! 
I downloaded the latest version and the code now works fine. Thank you for fixing this bug! 
Best, 
Simon
