### ISSUE TITLE
Prob_Obs_Test fails for output equations with known symbolic parameters

### ISSUE THREAD

**Issue by simon-hellmann** [afvillaverde/strike-goldd#12]
Hi everyone! 

I'm running observability and identifiability analyses on rational biological models from anaerobic digestion. 
In my models I have certain symbolic parameters in vector p that I wanna check for identifiability; also, there are other parameters, which I defined symbolically but I do NOT wanna check for identifiability (syms c1, c2...) 

My output equations involve terms that are dependent on those latter symbolic parameters (c1, c2...) that are not part of the vector p. 

If I choose FISPO as the algorithm, everything works fine. However, if opts.algorithm = 2 (Prob_Obs_Test), Matlab throws the following error (although my model equations are clearly rational): 

"Error using symengine
Polynomial expression expected."

If I redefine my parameters c1, c2... as numeric variables and assign them arbitrary values, Prob_Obs_Test works just fine. 
Maybe I'm stupid. But maybe there is a little bug in Prob_Obs_Test. 
Could you help me clarifying this issue? 

Attached is my code for model definition (as .txt, because .m doesn't seem to be supported). 

Thanks a lot and best wishes, 
Simon

[z_create_ADModel.txt](https://github.com/afvillaverde/strike-goldd/files/9785501/z_create_ADModel.txt)

**Comment by SandraDiazSeoane** [comment]
Hi, Simon.
Thanks for reposting the issue and sorry for the delay. I hope you have been able to continue working by using the FISPO algorithm. The bug was due to the appearance on the output of known parameters that are not in the function state, it is now fixed.
